---
- name: Ensure that the {{ protonvpn_package }} package is installed
  tags: protonvpn
  homebrew_cask:
    name: "{{ protonvpn_package|lower }}"
    state: present
  when: protonvpn_package|length > 0

- name: Attempting to apply {{ protonvpn_package }} configurations
  tags: protonvpn
  osx_defaults:
    domain: "{{ protonvpn_domain }}"
    key: "{{ item.name }}"
    state: "{{ item.state|default('present') }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
  loop: "{{ protonvpn_defaults }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - item.name is defined
    - item.type is defined
    - item.value is defined
    - protonvpn_defaults|length > 0
    - protonvpn_domain is defined
...
