---
- name: Ensure that the {{ protonvpn_package }} package is installed
  tags: protonvpn
  homebrew_cask:
    name: "{{ protonvpn_package|lower }}"
    state: present
  register: protonvpn_homebrew_cask

- name: Attempting to apply {{ protonvpn_package }} configurations
  tags: protonvpn
  osx_defaults:
    domain: "{{ protonvpn_domain }}"
    key: "{{ item.key|regex_replace('_', ' ') }}"
    state: "{{ item.value.state|default('present') }}"
    type: "{{ item.value.type }}"
    value: "{{ item.value.value }}"
  with_dict: "{{ protonvpn_defaults }}"
  when:
    - item.key is defined
    - item.value.type is defined
    - item.value.value is defined
    - protonvpn_defaults|length > 0
    - protonvpn_homebrew_cask is success
...
